name: Auto assign
on:
  workflow_call

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - name: 'Auto-assign'
      uses: pozil/auto-assign-issue@v2
      with:
        repo-token: ${{ secrets.GH_PAT_AUTO_ASSIGN }}
        teams: Engineering
        abortIfPreviousAssignees: true
        failsIfUsersCannotBeAssigned: true
